fzf-git widgets for zsh

diff --git a/shell/.config/zsh/functions/Misc/fzf-bindkey b/shell/.config/zsh/functions/Misc/fzf-bindkey
--- a/shell/.config/zsh/functions/Misc/fzf-bindkey
+++ b/shell/.config/zsh/functions/Misc/fzf-bindkey
@@ -1,10 +1,10 @@
 fzf-bindkey::print() {
-    if ! which bindkey 1>/dev/null 2>&1; then
-        echo 'A "bindkey" command is not found.'
-        return 1
-    fi
-    local s=$(bindkey -L | fzf --query "$1")
-    [[ -n $s ]] && print "$s"
+  if ! which bindkey 1>/dev/null 2>&1; then
+    echo 'A "bindkey" command is not found.'
+    return 1
+  fi
+  local s=$(bindkey -L | fzf --query "$1")
+  [[ -n $s ]] && print "$s"
 }
 
 [[ "x$BUFFER" != "x" ]] && BUFFER="$BUFFER "
diff --git a/shell/.config/zsh/functions/Misc/fzf-kill b/shell/.config/zsh/functions/Misc/fzf-kill
--- a/shell/.config/zsh/functions/Misc/fzf-kill
+++ b/shell/.config/zsh/functions/Misc/fzf-kill
@@ -1,15 +1,15 @@
 fzf-kill::print() {
-    if ! which ps 1>/dev/null 2>&1; then
-        echo 'A "ps" command is not found.'
-        return 1
-    fi
-    if ! which perl 1>/dev/null 2>&1; then
-        echo 'A "perl" command is not found.'
-        return 1
-    fi
-    local s=$(ps -ef \
-        | fzf --query "$1")
-    [[ -n $s ]] && print "kill $(echo $s | perl -lanE 'say $F[1]')"
+  if ! which ps 1>/dev/null 2>&1; then
+    echo 'A "ps" command is not found.'
+    return 1
+  fi
+  if ! which perl 1>/dev/null 2>&1; then
+    echo 'A "perl" command is not found.'
+    return 1
+  fi
+  local s=$(ps -ef \
+    | fzf --query "$1")
+  [[ -n $s ]] && print "kill $(echo $s | perl -lanE 'say $F[1]')"
 }
 
 [[ "x$BUFFER" != "x" ]] && BUFFER="$BUFFER "
